ALTER TABLE "User" ADD COLUMN "reminderEmails" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN "waitlistAlerts" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "Seat" ADD COLUMN "seatType" TEXT NOT NULL DEFAULT 'STANDARD';
ALTER TABLE "Seat" ADD COLUMN "aisleAfter" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Seat" ADD COLUMN "isBlocked" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Seat" ADD COLUMN "viewLabel" TEXT;
ALTER TABLE "Seat" ADD COLUMN "viewScore" INTEGER;

ALTER TABLE "ShowSeat" ADD COLUMN "unavailableReason" TEXT;
