import type { UserRole } from "@cinebook/shared";
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../lib/api";
import { AccessibleDialog } from "../components/AccessibleDialog";

type Overview = { stats: Record<string, number>; latestRun?: { status: string; startedAt: string } | null };
type City = { id: string; name: string; archivedAt?: string | null; _count: { venues: number } };
type User = { id: string; name: string; email: string; role: UserRole; _count: { bookings: number; events: number } };
type Auditorium = { id: string; name: string; archivedAt?: string | null; venue: { name: string; city: string }; _count: { shows: number } };
type VenueOption = { id: string; name: string; city: string; archivedAt?: string | null };
type Show = { id: string; title: string; date: string; time: string; status: string; organiser: { name: string; email: string }; venue: { name: string; city: string }; _count: { bookings: number; waitlist: number } };
type Booking = { id: string; ref: string; status: string; totalAmount: number; user: { name: string; email: string }; event: { title: string; organiser: { name: string }; venue: { name: string } }; seats: Array<{ seat: { label: string } }> };
type Job = { id: string; type: string; status: string; attempts: number; maxAttempts: number; availableAt: string; createdAt: string; completedAt?: string | null; lastError?: string | null };
type PreviewSummary = { id: string; kind: string; recipient: string; subject: string; relatedEntityId?: string | null; createdAt: string };
type EmailPreview = PreviewSummary & { textBody: string; htmlBody: string };
type Operations = { runs: Array<{ id: string; status: string; startedAt: string; completedAt?: string | null; error?: string | null }>; jobs: Job[]; previews: PreviewSummary[]; diagnostics: { redis: { configured: boolean; status: string; message: string; latencyMs?: number | null; endpoint?: string | null }; email: { configured: boolean; verified: boolean; mode: string; message: string } }; emailFailures: Array<{ kind: string; id: string; recipient: string; eventTitle: string; attempts: number; error?: string | null }> };
type Audit = { id: string; action: string; entityType: string; entityId?: string | null; createdAt: string; actor?: { name: string; email: string } | null };

export function AdminDashboardPage() {
  const [overview, setOverview] = useState<Overview | null>(null); const [cities, setCities] = useState<City[]>([]); const [users, setUsers] = useState<User[]>([]); const [auditoriums, setAuditoriums] = useState<Auditorium[]>([]); const [shows, setShows] = useState<Show[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [operations, setOperations] = useState<Operations | null>(null); const [audit, setAudit] = useState<Audit[]>([]);
  const [venues, setVenues] = useState<VenueOption[]>([]); const [cityName, setCityName] = useState(""); const [auditoriumName, setAuditoriumName] = useState(""); const [auditoriumVenueId, setAuditoriumVenueId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [selectedPreview, setSelectedPreview] = useState<EmailPreview | null>(null);
  const load = useCallback(async () => {
    const [overviewData, cityData, userData, auditoriumData, showData, bookingData, operationData, auditData, venueData] = await Promise.all([
      api<Overview>("/api/admin/overview"), api<{ cities: City[] }>("/api/admin/cities"), api<{ users: User[] }>("/api/admin/users?pageSize=100"), api<{ auditoriums: Auditorium[] }>("/api/admin/auditoriums"), api<{ shows: Show[] }>("/api/admin/shows?pageSize=100"), api<{ bookings: Booking[] }>("/api/admin/bookings?pageSize=100"), api<Operations>("/api/admin/operations"), api<{ logs: Audit[] }>("/api/admin/audit?pageSize=50"), api<{ venues: VenueOption[] }>("/api/venues")
    ]);
    setOverview(overviewData); setCities(cityData.cities); setUsers(userData.users); setAuditoriums(auditoriumData.auditoriums); setShows(showData.shows); setBookings(bookingData.bookings); setOperations(operationData); setAudit(auditData.logs); setVenues(venueData.venues.filter((venue) => !venue.archivedAt)); setAuditoriumVenueId((current) => current || venueData.venues.find((venue) => !venue.archivedAt)?.id || "");
  }, []);
  useEffect(() => { load().catch((reason) => setError(reason instanceof Error ? reason.message : "Administration data could not be loaded")); }, [load]);
  async function perform(action: () => Promise<unknown>, success: string) { setBusy(true); setError(""); setMessage(""); try { await action(); setMessage(success); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Action failed"); } finally { setBusy(false); } }
  async function openPreview(id: string) { setBusy(true); setError(""); try { const result = await api<{ preview: EmailPreview }>(`/api/admin/email-previews/${id}`); setSelectedPreview(result.preview); } catch (reason) { setError(reason instanceof Error ? reason.message : "Email preview could not be loaded"); } finally { setBusy(false); } }
  const stats = overview?.stats ?? {};
  return <section className="workspace-page admin-console">
    <header className="workspace-heading"><div><p className="kicker">Platform administration</p><h1>Operations command centre.</h1><p>Manage access, catalogue infrastructure, bookings, deliveries, and platform health without database access.</p></div><Link className="button button-ghost" to="/admin/venues">Venue layouts</Link></header>
    {(error || message) && <p className={error ? "form-message error" : "inline-notice"} role={error ? "alert" : "status"}>{error || message}</p>}
    <div className="metric-grid admin-metrics">{["users", "organisers", "venues", "shows", "published", "bookings", "revenue", "waitlisted", "emailFailures"].map((key) => <article className="metric-card" key={key}><small>{key.replace(/([A-Z])/g, " $1")}</small><strong>{key === "revenue" ? `₹${(stats[key] ?? 0).toLocaleString("en-IN")}` : (stats[key] ?? 0).toLocaleString("en-IN")}</strong><span>Live platform total</span></article>)}</div>

    <div className="admin-section-grid">
      <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Locations</p><h2>Managed cities</h2></div><form className="inline-create" onSubmit={(event) => { event.preventDefault(); perform(() => api("/api/admin/cities", { method: "POST", body: JSON.stringify({ name: cityName }) }), "City created.").then(() => setCityName("")); }}><input aria-label="New city name" className="form-control" value={cityName} onChange={(event) => setCityName(event.target.value)} placeholder="New city" required /><button className="button button-primary compact" disabled={busy}>Add</button></form></div><div className="compact-list">{cities.map((city) => <div key={city.id}><span><strong>{city.name}</strong><small>{city._count.venues} venues · {city.archivedAt ? "Archived" : "Active"}</small></span><button type="button" disabled={busy} onClick={() => perform(() => api(`/api/admin/cities/${city.id}`, { method: "PATCH", body: JSON.stringify({ archived: !city.archivedAt }) }), city.archivedAt ? "City restored." : "City archived.")}>{city.archivedAt ? "Restore" : "Archive"}</button></div>)}</div></section>
      <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Screens</p><h2>Auditoriums</h2></div><form className="inline-create" onSubmit={(event) => { event.preventDefault(); perform(() => api("/api/admin/auditoriums", { method: "POST", body: JSON.stringify({ venueId: auditoriumVenueId, name: auditoriumName }) }), "Auditorium created.").then(() => setAuditoriumName("")); }}><select aria-label="Auditorium venue" className="form-control" value={auditoriumVenueId} onChange={(event) => setAuditoriumVenueId(event.target.value)} required>{venues.map((venue) => <option value={venue.id} key={venue.id}>{venue.name}</option>)}</select><input aria-label="New auditorium name" className="form-control" value={auditoriumName} onChange={(event) => setAuditoriumName(event.target.value)} placeholder="Screen name" required /><button className="button button-primary compact" disabled={busy}>Add</button></form></div><div className="compact-list">{auditoriums.map((room) => <div key={room.id}><span><strong>{room.name}</strong><small>{room.venue.name}, {room.venue.city} · {room._count.shows} shows</small></span><button type="button" disabled={busy} onClick={() => perform(() => api(`/api/admin/auditoriums/${room.id}`, { method: "PATCH", body: JSON.stringify({ archived: !room.archivedAt }) }), room.archivedAt ? "Auditorium restored." : "Auditorium archived.")}>{room.archivedAt ? "Restore" : "Archive"}</button></div>)}</div></section>
    </div>

    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Identity and access</p><h2>Users and roles</h2></div></div><div className="data-table"><div className="data-row data-head"><span>Name</span><span>Email</span><span>Activity</span><span>Role</span><span>Access</span></div>{users.map((user) => <div className="data-row" key={user.id}><strong>{user.name}</strong><span>{user.email}</span><span>{user._count.bookings} bookings · {user._count.events} shows</span><span>{user.role}</span><select aria-label={`Role for ${user.name}`} className="form-control" value={user.role} disabled={busy} onChange={(event) => perform(() => api(`/api/admin/users/${user.id}/role`, { method: "PATCH", body: JSON.stringify({ role: event.target.value }) }), "User role updated.")}>{["CUSTOMER", "ORGANISER", "ADMIN"].map((role) => <option key={role}>{role}</option>)}</select></div>)}</div></section>

    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Cross-organiser catalogue</p><h2>Shows</h2></div></div><div className="data-table"><div className="data-row data-head"><span>Show</span><span>Organiser</span><span>Venue</span><span>Status</span><span>Demand</span></div>{shows.map((show) => <div className="data-row" key={show.id}><strong>{show.title}<small>{show.date} · {show.time}</small></strong><span>{show.organiser.name}<small>{show.organiser.email}</small></span><span>{show.venue.name}<small>{show.venue.city}</small></span><span>{show.status}</span><span>{show._count.bookings} bookings · {show._count.waitlist} waitlist</span></div>)}</div></section>
    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Platform sales</p><h2>Bookings</h2></div></div><div className="data-table"><div className="data-row data-head"><span>Reference</span><span>Customer</span><span>Show</span><span>Seats</span><span>Total</span></div>{bookings.map((booking) => <div className="data-row" key={booking.id}><strong>{booking.ref}<small>{booking.status}</small></strong><span>{booking.user.name}<small>{booking.user.email}</small></span><span>{booking.event.title}<small>{booking.event.organiser.name} · {booking.event.venue.name}</small></span><span>{booking.seats.map(({ seat }) => seat.label).join(", ")}</span><strong>₹{booking.totalAmount.toLocaleString("en-IN")}</strong></div>)}</div></section>

    <div className="admin-section-grid"><section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Background jobs</p><h2>Maintenance</h2></div><button type="button" className="button button-primary compact" disabled={busy} onClick={() => perform(() => api("/api/admin/operations/run", { method: "POST" }), "Maintenance completed.")}>Run now</button></div><div className="compact-list">{operations?.runs.map((run) => <div key={run.id}><span><strong>{run.status}</strong><small>{new Date(run.startedAt).toLocaleString("en-IN")}</small></span>{run.error && <small className="error-text">{run.error}</small>}</div>)}{!operations?.runs.length && <p className="muted-copy">No recorded maintenance runs.</p>}</div></section><section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Delivery recovery</p><h2>Failed emails</h2></div></div><div className="compact-list">{operations?.emailFailures.map((failure) => <div key={`${failure.kind}-${failure.id}`}><span><strong>{failure.eventTitle}</strong><small>{failure.recipient} · {failure.attempts} attempts</small></span><button type="button" disabled={busy} onClick={() => perform(() => api(`/api/admin/email/${failure.kind}/${failure.id}/retry`, { method: "POST" }), "Email retry completed.")}>Retry</button></div>)}{!operations?.emailFailures.length && <p className="muted-copy">No failed deliveries.</p>}</div></section></div>
    <div className="admin-section-grid operations-diagnostics">
      <section className="workspace-card data-table-card"><p className="kicker">Realtime coordination</p><h2>Redis diagnostics</h2><div className={`diagnostic-state ${operations?.diagnostics.redis.status ?? "disabled"}`}><strong>{operations?.diagnostics.redis.status ?? "Loading"}</strong><span>{operations?.diagnostics.redis.message}</span><small>{operations?.diagnostics.redis.endpoint ?? "Local fallback"}{operations?.diagnostics.redis.latencyMs != null ? ` · ${operations.diagnostics.redis.latencyMs} ms` : ""}</small></div></section>
      <section className="workspace-card data-table-card"><p className="kicker">Notification transport</p><h2>Email diagnostics</h2><div className={`diagnostic-state ${operations?.diagnostics.email.verified ? "connected" : "preview"}`}><strong>{operations?.diagnostics.email.mode ?? "Loading"}</strong><span>{operations?.diagnostics.email.message}</span><small>{operations?.diagnostics.email.verified ? "External delivery verified" : "Every message is stored as a local preview"}</small></div></section>
    </div>
    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Durable queue</p><h2>Background job monitor</h2></div><span className="workspace-chip">{operations?.jobs.length ?? 0} recent jobs</span></div><div className="data-table job-table"><div className="data-row data-head"><span>Job</span><span>Status</span><span>Attempts</span><span>Scheduled</span><span>Action</span></div>{operations?.jobs.map((job) => <div className="data-row" key={job.id}><strong>{job.type.replaceAll("_", " ")}<small>{job.id}</small></strong><span className={`job-status ${job.status.toLowerCase()}`}>{job.status}</span><span>{job.attempts} / {job.maxAttempts}</span><span>{new Date(job.availableAt).toLocaleString("en-IN")} {job.lastError && <small className="error-text">{job.lastError}</small>}</span><span>{["FAILED", "RETRY"].includes(job.status) ? <button type="button" disabled={busy} onClick={() => perform(() => api(`/api/admin/jobs/${job.id}/retry`, { method: "POST" }), "Background job retried.")}>Retry now</button> : "—"}</span></div>)}</div></section>
    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Local notification studio</p><h2>Email previews</h2></div><div className="toolbar-actions"><span className="workspace-chip">No email account required</span><button type="button" className="button button-ghost compact" disabled={busy} onClick={() => perform(() => api("/api/admin/email-previews/samples", { method: "POST" }), "Sample previews generated for every notification.")}>Generate all samples</button></div></div><div className="compact-list">{operations?.previews.map((preview) => <div key={preview.id}><span><strong>{preview.subject}</strong><small>{preview.kind.replaceAll("_", " ")} · {preview.recipient} · {new Date(preview.createdAt).toLocaleString("en-IN")}</small></span><button type="button" disabled={busy} onClick={() => openPreview(preview.id)}>Preview</button></div>)}{!operations?.previews.length && <p className="muted-copy">Notification previews appear here after the worker processes a job.</p>}</div></section>
    {selectedPreview && <AccessibleDialog labelledBy="preview-title" className="email-preview-dialog" onClose={() => setSelectedPreview(null)}><div className="panel-toolbar"><div><p className="kicker">{selectedPreview.kind.replaceAll("_", " ")}</p><h2 id="preview-title">{selectedPreview.subject}</h2><p>{selectedPreview.recipient}</p></div><button type="button" className="button button-ghost compact" onClick={() => setSelectedPreview(null)}>Close</button></div><iframe title="Rendered email preview" sandbox="" srcDoc={selectedPreview.htmlBody} /><details><summary>Plain-text version</summary><pre>{selectedPreview.textBody}</pre></details></AccessibleDialog>}
    <section className="workspace-card data-table-card"><div className="panel-toolbar"><div><p className="kicker">Accountability</p><h2>Administrator audit log</h2></div></div><div className="data-table"><div className="data-row data-head"><span>Action</span><span>Entity</span><span>Administrator</span><span>Time</span><span>ID</span></div>{audit.map((log) => <div className="data-row" key={log.id}><strong>{log.action.replaceAll("_", " ")}</strong><span>{log.entityType}</span><span>{log.actor?.name ?? "System"}<small>{log.actor?.email}</small></span><span>{new Date(log.createdAt).toLocaleString("en-IN")}</span><code>{log.entityId ?? "—"}</code></div>)}</div></section>
  </section>;
}
